# Generated by Django 4.2.11 on 2024-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scname', models.CharField(max_length=100)),
                ('Scprincipal', models.CharField(max_length=100)),
                ('Sclocation', models.CharField(max_length=100)),
            ],
        ),
    ]
